[package]
name = "ads_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.5.4", features = ["derive"]}
jwalk = "0.8.1"

[target.'cfg(target_os="linux")'.dependencies]
xattr = "1.3.1"
sys-mount = "3.0.1"